name: "Build"
on:
  pull_request:
  push:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v8
      with:
        name: nix-community
        skipNixBuild: true
    - uses: cachix/cachix-action@v8
      with:
        name: mjlbach
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#emacsPgtkGcc'
    - run: nix-shell --run "echo OK"
  build-macos:
     runs-on: macos-10.14
     steps:
     - uses: actions/checkout@v2.3.4
     - uses: cachix/install-nix-action@v12
       with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
        extra_nix_config: |
           experimental-features = nix-command flakes
     - uses: cachix/cachix-action@v8
       with:
         name: nix-community
         skipNixBuild: true
     - uses: cachix/cachix-action@v8
       with:
         name: mjlbach
         signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
         # Only needed for private caches
         #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
     - run: nix build '.#emacsGcc'
     - run: nix-shell --run "echo OK"

