name: Update Flake

on:
  schedule:
    # every day at 8am UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20201007_5257a25/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix flake update --recreate-lock-file
    - uses: cachix/cachix-action@v8
      with:
        name: mjlbach
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        #    - run: nix-build
    # - run: nix-shell --run "pre-commit run -a"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        commit-message: "[automation] update niv dependencies"
        title: "[automation] update niv dependencies"
        branch: "automation/update-niv-dependencies"
